### ISSUE TITLE
Colormap Choice and normalization

### ISSUE THREAD

**Issue by luisortizuriarte** [nblancoalcala/HW1_clim_680#3]
Precipitation is an interesting quantity because it often has 0 values over large areas. You might be better served by a non-linear (e.g., logarithmic normalization https://matplotlib.org/stable/users/explain/colors/colormapnorms.html) to better represent your data. 

The colormap selected is a diverging map, which is best used for data that has a split (think negative/positive anomalies) or sometimes for process we associate going to cool to warm (blue to red?) colors like temperature. You might be better served by a different colormap here to show your data.

**Comment by nblancoalcala** [comment]
I have fixed my map. Also, the dataset I chose only show the positive values according to the website I got it from. They say " We stored all values where the values were >0."

**Comment by luisortizuriarte** [comment]
Looks great! Closing issue.
